name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello I am Vishwanath!"
   notify:
     needs: my-jobs
      runs-on: ubuntu-latest
      steps:
       - name: my-step
         run: echo "How are you Vishwanath"
